In [2]:
import pandas as pd
seeddata = pd.read_csv('seed.txt','\t',header=None)
seeddata

         0      1       2      3      4      5      6  7
0    15.26  14.84  0.8710  5.763  3.312  2.221  5.220  1
1    14.88  14.57  0.8811  5.554  3.333  1.018  4.956  1
2    14.29  14.09  0.9050  5.291  3.337  2.699  4.825  1
3    13.84  13.94  0.8955  5.324  3.379  2.259  4.805  1
4    16.14  14.99  0.9034  5.658  3.562  1.355  5.175  1
..     ...    ...     ...    ...    ...    ...    ... ..
205  12.19  13.20  0.8783  5.137  2.981  3.631  4.870  3
206  11.23  12.88  0.8511  5.140  2.795  4.325  5.003  3
207  13.20  13.66  0.8883  5.236  3.232  8.315  5.056  3
208  11.84  13.21  0.8521  5.175  2.836  3.598  5.044  3
209  12.30  13.34  0.8684  5.243  2.974  5.637  5.063  3

[210 rows x 8 columns]

In [15]:
from sklearn.linear_model import LogisticRegression
X=seeddata.iloc[:,0:7]
y=seeddata.iloc[:,7]
clf = LogisticRegression(random_state=0).fit(X, y)
print(clf.predict(X[0:2]))

#clf.predict_proba(X[0:2])

print(clf.score(X, y))

[1 1]
0.9285714285714286

D:\anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(